profile = "andyt-develeap"
default_tags = ["andyt","19","22-09-2024"]
name_prefix = "andy"
subnet_count = 3
availability_zones = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
instance_types = ["t3a.medium"]
vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_offset = 8
argocd_values_filepath = "./argocd-files/argocd-values.yaml"
ng_max_size = 3
ng_min_size = 1
ng_desired_size = 2
ng_max_unavailable = 1
