configs:
  secret:
    createSecret: true
    argocdServerAdminPassword: "$2b$12$/HZfU/g2aoHv89JxBHphVeAFIb6bf2S5fwiAsgr1s8z/XzxxHZ8Uq" # Base64 Blowfish encryption cipher
  params:
    server.insecure: true
    
server:
  ingress:
    enabled: true
    # annotations:
    #   cert-manager.io/cluster-issuer: "letsencrypt"
    ingressClassName: "nginx"
    hosts: ["ourlibargo.ddns.net"]
    # tls:
    #   - hosts: ["ourlibargo.ddns.net"]
    #     secretName: argocd-server-tls
    # https: true